FROM ubuntu
RUN apt update -y &&\
    apt install default-jdk -y &&\
    java -version
RUN apt install maven -y &&\
    mvn -version
RUN apt install -y wget 
RUN wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz
RUN mkdir /opt/tomcat &&\
    tar -xvzf apache-tomcat-9.0.8.tar.gz -C /opt/tomcat --strip-components=1 &&\
    rm apache-tomcat-9.0.8.tar.gz
RUN groupadd tomcat &&\
    useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
RUN chmod 755 /opt/tomcat/conf /opt/tomcat/bin &&\
    chown -R tomcat:tomcat /opt/tomcat/webapps/ /opt/tomcat/work/ /opt/tomcat/temp/ /opt/tomcat/logs/ /opt/tomcat/bin/ &&\
    chmod +x /opt/tomcat/bin/*.sh
ENTRYPOINT ["sh","/opt/tomcat/bin/startup.sh"]
